runtime: python27
api_version: 1
threadsafe: true
application: everyidea-166123
version: 1

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /assets
  static_dir: assets
  
- url: /images
  static_dir: images
  
- url: /.*
  script: everyidea.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
